dist: trusty
language: minimal
sudo: false

env:
  global:
    - fast_finish: true
    - DOCKER_NAMESPACE=lansible
    - CONTAINER_NAME=git-clone

services:
  - docker

script:
  # Try to pull tag but when empty pull branch_name
  # If successful use as build cache
  - |
    docker pull "${DOCKER_NAMESPACE}/${CONTAINER_NAME}:${TRAVIS_TAG:-${TRAVIS_BRANCH}}"
    if [[ $? ]]
    then
      CACHE="--cache-from ${DOCKER_NAMESPACE}/${CONTAINER_NAME}:${TRAVIS_BRANCH}"
    fi
    echo "CACHE is ${CACHE}"
  - |
    BUILD_TAGS="-t ${DOCKER_NAMESPACE}/${CONTAINER_NAME}:${TRAVIS_BRANCH}"
    if [[ ${TRAVIS_TAG} != "" ]]
    then
      BUILD_TAGS+=" -t ${DOCKER_NAMESPACE}/${CONTAINER_NAME}:latest"
    fi
    echo "BUILD_TAGS are ${BUILD_TAGS}"
  - docker build . ${CACHE} ${BUILD_TAGS}

deploy:
  provider: script
  script: bash deploy/deploy.sh
  on:
    all_branches: true

notifications:
  email:
    on_failure: change
    on_success: never
