dist: trusty
language: minimal
sudo: false

env:
  global:
    - fast_finish: true
    - DOCKER_NAMESPACE=lansible
    - CONTAINER_NAME=git-clone

services:
  - docker

before_script:
  - docker pull ${DOCKER_NAMESPACE}/${CONTAINER_NAME}:latest

script:
  - |
    if [[ ${TRAVIS_TAG} == ${TRAVIS_BRANCH} ]]
    then
      TAG_STRING=" \
        -t ${DOCKER_NAMESPACE}/${CONTAINER_NAME}:${TRAVIS_TAG} \
        -t ${DOCKER_NAMESPACE}/${CONTAINER_NAME}:latest"
    elif [[ ! ${TRAVIS_PULL_REQUEST} ]]
    then
      TAG_STRING=" \
        -t ${DOCKER_NAMESPACE}/${CONTAINER_NAME}:${TRAVIS_BRANCH}"
    fi
    docker build . --cache-from ${DOCKER_NAMESPACE}/${CONTAINER_NAME}:latest ${TAG_STRING}

deploy:
  provider: script
  script: bash deploy/deploy.sh
  on:
    branch: master
  skip_cleanup: true

notifications:
  email:
    on_failure: change
    on_success: never
